services:
  - type: web
    name: laravel-api
    env: php
    plan: free
    buildCommand: |

      apt-get update && apt-get install -y php-pgsql && composer install --no-dev
      composer install --optimize-autoloader --no-dev
      php artisan migrate 
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
      php artisan config:clear
      php artisan cache:clear
      php artisan migrate
      php artisan migrate:status

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d495b2f5r7bs738v8t60-a.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: lawfirm_backend_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: xEYuxPeETFAISUmTxeP9XRHca5koIyFW
